import FooterSection from "@/components/shared/footer";
import Navbar from "@/components/shared/navbar";
import ScrollToTop from "@/components/shared/scroll-to-top";
import "../styles/globals.css";

export const metadata = {
  title: "Sheba",
  description: "Generated by pixels web makers.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <header>
          <Navbar />
        </header>
        <main>{children}</main>
        <footer>
          <FooterSection />
        </footer>
        <ScrollToTop />
      </body>
    </html>
  );
}
