import FooterSection from "@/components/shared/footer";
import Navbar from "@/components/shared/navbar";
import ScrollToTop from "@/components/shared/scroll-to-top";
import "../styles/globals.css";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Adhunik BD",
  description: "Generated by pixels web makers.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Toaster position="top-center" reverseOrder={false} />
        <main>{children}</main>
      </body>
    </html>
  );
}
